### ISSUE TITLE
Step 4, point 2 is incomplete

### ISSUE THREAD

**Issue by perryahern** [LambdaSchool/Sprint-Challenge-Authentication#61]
`Send a GET request up to /api/jokes with the appropriate`

Appropriate what? It needs the token, so it seems this should say 'with the appropriate token.'

Also we need to know that the header key in Postman needs to be named "Authorization" for this to work.

**Comment by mixelpixel** [comment]
@perryahern Would something like this suffice?

> Send a `GET` request up to `/api/jokes` endpoint with the appropriate **Header** from your logged in user's **Authorization** token

@ryanhca This is now Step 4, line 66
> Send a `GET` request up to `/api/jokes` with the appropriate

There was considerable confusion in CS7 yesterday about how to do this with Postman:

![screen shot 2018-03-24 at 4 48 12 pm](https://user-images.githubusercontent.com/18152993/37868822-5fdc8e84-2f83-11e8-8649-b3d94edecdbc.png)


...especially given the "Authorizations" and "Headers" settings tabs available in the Postman UI.

Also a couple students that thought they had to implement something extra - one was pleasantly surprised in their review when I showed them that their code worked and ended up changing their self-evaluation from a 1 to a 2 😊

FWIW, with cURL, the command is like so:

`curl http://localhost:5000/api/jokes -H "Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2V
ybmFtZSI6ImRhbmkiLCJpYXQiOjE1MjE5MjQyODV9.hyV-8LYUBBGMYPCZIv3QU7oQ2z5iBRGIfYHPpE9LKiY"`

i.e. `curl <route> -H "Authorization:token"`

**Comment by mixelpixel** [comment]
Just for my own reference, cURL equivalents:

/api/users/
i.e. `curl -x HTTP_METHOD <route> -H {CONTENT_TYPE} -d '{"JSON":"DATA"}'
```console
$  curl -X POST http://localhost:5000/api/users -H 'Content-Type: application/json' -d '{"username":"cool_name","password":"reallydifficult"}'
    {
     "__v":0,
     "username":"cool_name",
     "password":"$2a$11$ZziXrc/QXfPxm42WWLPPJ.JyvQS.ClyBnPDYvdclDUv06v9Uaiwhu",
     "_id":"5ab6c702ae098de170987a00"
    }
```


/api/login/
i.e. `curl -x HTTP_METHOD <route> -H {CONTENT_TYPE} -d '{"JSON":"DATA"}'
```console
$  curl -X POST http://localhost:5000/api/login -H 'Content-Type: application/json' -d '{"username":"cool_name","password":"reallydifficult"}'
    {
     "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNvb2xfbmFtZSIsImlhdCI6MTUyMTkyODA5Mn0.8aSKqHzQkprobO5w4oo-SuC03M4YIYFyPCD9EVNXu_s"
    }
```

/api/jokes:
i.e. `curl <route> -H "Authorization:token"`
```console
$ curl http://localhost:5000/api/jokes -H "Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNvb2xfbmFtZSIsImlhdCI6MTUyMTkyODA5Mn0.8aSKqHzQkprobO5w4oo-SuC03M4YIYFyPCD9EVNXu_s"
[
    {
        "id": 30,
        "type": "programming",
        "setup": "Two bytes meet. The first byte asks, \"Are you ill?\"",
        "punchline": "The second byte replies, \"No, just feeling a bit off.\""
    },
    {
        "id": 8,
        "type": "general",
        "setup": "How do you organize an outer space party?",
        "punchline": "You planet"
    },
    {
        "id": 30,
        "type": "programming",
        "setup": "Two bytes meet. The first byte asks, \"Are you ill?\"",
        "punchline": "The second byte replies, \"No, just feeling a bit off.\""
    },
    {
        "id": 19,
        "type": "knock-knock",
        "setup": "Knock knock. \n Who's there? \n Alex. \n Alex who?",
        "punchline": "ALex the questions around here!"
    },
    {
        "id": 4,
        "type": "general",
        "setup": "What do you call a belt made out of watches?",
        "punchline": "A waist of time."
    },
    {
        "id": 5,
        "type": "general",
        "setup": "Why can't bicycles stand on their own?",
        "punchline": "They are two tired"
    },
    {
        "id": 13,
        "type": "knock-knock",
        "setup": "Knock knock. \n Who's there? \n Little old lady. \n Little old lady who?",
        "punchline": "I didn't know you could yodel!"
    },
    {
        "id": 29,
        "type": "programming",
        "setup": "A foo walks into a bar, takes a look around and says...",
        "punchline": "Hello, World!"
    },
    {
        "id": 8,
        "type": "general",
        "setup": "How do you organize an outer space party?",
        "punchline": "You planet"
    },
    {
        "id": 3,
        "type": "general",
        "setup": "What's Forrest Gump's password?",
        "punchline": "1Forrest1"
    }
]
```
